# Generated by Django 2.2.2 on 2019-08-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bab_app', '0007_post_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starzip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('star_rating', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bab_app.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
